version: '3'
services:
  registry:
    build:
      context: ./registry
      dockerfile: Dockerfile
    volumes:
      - ./registry/:/app
    ports:
      - "9000:9000"
  peer1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - CONFIG_PATH=dump/peer1/config.json
    ports:
      - "8001:8001"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8001
    depends_on:
      - registry
  peer2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - CONFIG_PATH=dump/peer2/config.json
    ports:
      - "8002:8002"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8002
    depends_on:
      - registry
